wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1673444818.525384
    t:
      1:
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.7
      8:
      - 1
      - 4
      - 5
comment:
  desc: null
  value: 'Description: extra comment from training notebook'
